services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: production_database
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    tmpfs:
      - /var/lib/redis/data
    networks:
      - app_network

  migrate:
    image: game_session_logger:latest
    container_name: alembic_migration
    environment:
      - DATABASE_URL=postgresql+psycopg2://app_user:app_password@db/production_database
    entrypoint: ["/.venv/bin/python", "-m", "alembic", "upgrade", "head"]
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
