services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: production_database
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  web:
    image: game_session_logger:latest
    container_name: game_session_logger
    environment:
      - DATABASE_URL=postgresql+asyncpg://app_user:app_password@db/production_database
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  celery_worker:
    image: game_session_logger:latest
    container_name: celery_worker
    entrypoint: [ "/.venv/bin/python", "-m", "celery", "-A", "app.expired_sessions_cleaner", "worker", "--loglevel=info" ]
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app_network

  celery_beat:
    image: game_session_logger:latest
    container_name: celery_beat
    entrypoint: [ "/.venv/bin/python", "-m", "celery", "-A", "app.expired_sessions_cleaner", "beat", "--loglevel=info" ]
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge