version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: production_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  web:
    build:
      context: .
    container_name: fastapi_app
    environment:
      - DATABASE_URL=mysql+asyncmy://app_user:app_password@db/production_database
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge