version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_test_db
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    networks:
      - app_network

  web_test:
    build:
      context: .
      args:
        ENV: test
    container_name: game_session_logger
    environment:
      - DATABASE_URL=postgresql+asyncpg://test_user:test_password@db/test_database
    command: ["pytest", "--disable-warnings"]
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge