version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql_test_db
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3307:3306"
    networks:
      - app_network

  web_test:
    build:
      context: .
      args:
        ENV: test
    container_name: fastapi_test_app
    environment:
      - DATABASE_URL=mysql+asyncmy://test_user:test_password@db/test_database
    command: ["pytest", "--disable-warnings"]
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge