services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: production_database
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  migrate:
    image: game_session_logger:latest
    container_name: alembic_migration
    environment:
      - DATABASE_URL=postgresql+psycopg2://app_user:app_password@db/production_database
    entrypoint: ["python", "-m", "alembic", "upgrade", "head"]
    depends_on:
      - db
    networks:
      - app_network

  tests:
    image: game_session_logger:latest
    container_name: test_runner
    environment:
      - DATABASE_URL=postgresql+asyncpg://app_user:app_password@db/production_database
      - REDIS_URL=redis://redis_cache:6379/0
    entrypoint: ["python", "-m", "pytest", "-m", "tests/unit", "-v", "--log-cli-level=DEBUG"]
    depends_on:
      - db
      - redis
      - migrate
    networks:
      - app_network
    volumes:
      - ./:/app

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge
