"""Added last heartbit field

Revision ID: e9bdaa05c0c5
Revises: ba3ca466f77f
Create Date: 2024-10-26 23:03:54.981555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9bdaa05c0c5'
down_revision: Union[str, None] = 'ba3ca466f77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('last_heartbeat', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'last_heartbeat')
    # ### end Alembic commands ###
