# Start a new session
POST http://localhost:8000/sessions/start/
Content-Type: application/json

{
  "user_id": "test_user",
  "platform": "Linux"
}

###

# Get a created session by session_id
GET http://localhost:8000/sessions/{{session_id}}
Accept: application/json

###

# Send a heartbeat to an existing session
POST http://localhost:8000/sessions/heartbeat/{{session_id}}
Accept: application/json

###

# End expired sessions
DELETE http://localhost:8000/sessions/end_expired?expired_time={{expired_time}}
Accept: application/json